### ISSUE TITLE
Not starting up

### ISSUE THREAD

**Issue by ofcJakes** [scottcl88/MMM-DynamicWeather#51] opened 2024-05-12 11:16 UTC
**Have you tried all steps under [Troublehsooting](https://github.com/scottcl88/MMM-DynamicWeather/wiki/Troubleshooting)?**
Yes

**Describe the bug**
Hi I followed all the steps correctly(have repeated it from github 4 times) not sure where Im going wrong but when I launch magicmirror after editing my config file it doesnt launch but says its running. I have left it for an hour on and still doesnt show?
I have installed this module before on my rasp pi 3B and it worked great, atm Im working on a pi 5 8G

**Configuration**
		{
			module: 'MMM-DynamicWeather',
 			position: 'top_bar',
			config: { // See https://github.com/scottcl88/MMM-DynamicWeather for more information.
  			api_key: "My Api",
  			locationID: "993800",
			effects: [
   			  {
    				alwaysDisplay: "rain-lightning",
			  }
			],
 			  }
		},

**Expected behavior**
Always raining over the lofi wallpaper

**Screenshots**
Its just my desktop

**Additional context**
even using the original config settings it still doesnt boot?

**Comment by Pakatorius** [comment] 2024-05-13 22:36
Same.
New to MM but happy to help problem solve.
MM and all other modules I'm using are working great, but with DynamicWeather enabled MM will not restart.

**Comment by scottcl88** [comment] 2024-05-13 23:25
This is likely due to the known issue of a dependency not being imported manually. I just fixed it. If you still have issues, please review the troubleshooting steps and include log information. [https://github.com/scottcl88/MMM-DynamicWeather/wiki/Troubleshooting](Wiki Troubleshooting)

Closing as duplicate of #45

**Closed by scottcl88** 2024-05-13 23:25 UTC
Labels: bug
